import { Hono } from 'hono';

export const nodeTypeRoutes = new Hono();

// 返回所有可用节点类型及其 Schema（前端渲染用）
nodeTypeRoutes.get('/', (c) => {
  return c.json({ nodeTypes: NODE_TYPES });
});

// ── 节点类型定义 ──

const NODE_TYPES = [
  // 数据源
  {
    type: 'memory-search',
    category: 'source',
    label: '搜索记忆',
    description: '语义搜索 MiniMem 记忆',
    icon: 'search',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '记忆列表', type: 'memories' }],
    configSchema: {
      query: { type: 'string', label: '搜索关键词', required: true, template: true, placeholder: '最近的工作进展', description: '用自然语言描述你想找的记忆，支持语义匹配' },
      top_k: { type: 'number', label: '返回数量', default: 20, placeholder: '20', description: '最多返回多少条记忆，建议 10-50' },
      time_from: { type: 'string', label: '开始时间', template: true, placeholder: '2025-01-01 或 {{$date_offset(-7d)}}', description: '格式：YYYY-MM-DD，支持模板变量如 {{$date_offset(-7d)}} 表示7天前' },
      time_to: { type: 'string', label: '结束时间', template: true, placeholder: '2025-12-31 或 {{$date}}', description: '格式：YYYY-MM-DD，{{$date}} 表示今天' },
      domain: { type: 'string', label: '领域', template: true, placeholder: 'tech、health、work...', description: '按记忆所属领域过滤，如 tech(技术)、health(健康)、work(工作)、life(生活)' },
      layer: { type: 'select', label: '层级', options: ['', 'L1', 'L2', 'L3', 'L4'], optionLabels: ['全部层级', 'L1 - 原始记忆（对话片段）', 'L2 - 摘要记忆（日/周总结）', 'L3 - 知识记忆（实体关系）', 'L4 - 元认知（个人模式）'], description: '记忆层级：L1 原始 → L2 摘要 → L3 知识 → L4 元认知' },
      source: { type: 'string', label: '来源', template: true, placeholder: 'agent、user、minimem-console...', description: '记忆的写入来源，如 agent(AI助手)、user(手动写入)、minimem-console 等' },
    },
  },
  {
    type: 'memory-list',
    category: 'source',
    label: '浏览记忆',
    description: '分页浏览记忆列表',
    icon: 'list',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '记忆列表', type: 'memories' }],
    configSchema: {
      page: { type: 'number', label: '页码', default: 1, description: '从第几页开始，默认第 1 页' },
      page_size: { type: 'number', label: '每页数量', default: 50, description: '每页返回多少条，建议 20-100' },
      source: { type: 'string', label: '来源', placeholder: 'agent、user、minimem-console...', description: '按来源过滤，留空返回全部' },
      layer: { type: 'select', label: '层级', options: ['', 'L1', 'L2', 'L3', 'L4'], optionLabels: ['全部层级', 'L1 - 原始记忆', 'L2 - 摘要记忆', 'L3 - 知识记忆', 'L4 - 元认知'], description: '留空获取所有层级' },
    },
  },
  {
    type: 'memory-recall',
    category: 'source',
    label: '实体召回',
    description: '按实体名关联召回记忆',
    icon: 'user',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '记忆列表', type: 'memories' }],
    configSchema: {
      entity: { type: 'string', label: '实体名', required: true, template: true, placeholder: '张三、React、MiniMem...', description: '输入人名、技术名词、项目名等实体，召回所有关联记忆' },
    },
  },
  {
    type: 'static-text',
    category: 'source',
    label: '静态文本',
    description: '输入一段静态文本',
    icon: 'text',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '文本', type: 'text' }],
    configSchema: {
      text: { type: 'textarea', label: '文本内容', required: true, template: true, placeholder: '你好，今天是 {{$date}}，请帮我分析...', description: '直接输入文本内容，可用模板变量动态替换' },
    },
  },
  {
    type: 'surface-load',
    category: 'source',
    label: '加载 Surface',
    description: '加载 Surface Files',
    icon: 'file-text',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: 'Surfaces', type: 'json' }],
    configSchema: {
      agent_type: { type: 'string', label: 'Agent 类型', placeholder: 'assistant、scheduler...', description: '留空加载全部 Surface，填写则只加载对应 Agent 类型的' },
    },
  },
  {
    type: 'health-check',
    category: 'source',
    label: '健康检查',
    description: '获取 MiniMem 健康/统计数据',
    icon: 'activity',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '健康数据', type: 'json' }],
    configSchema: {},
  },
  {
    type: 'stats',
    category: 'source',
    label: '统计数据',
    description: '获取各层记忆数量统计',
    icon: 'bar-chart',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '统计', type: 'json' }],
    configSchema: {},
  },
  {
    type: 'temperature',
    category: 'source',
    label: '温度分布',
    description: '获取记忆温度分布',
    icon: 'thermometer',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '温度分布', type: 'json' }],
    configSchema: {},
  },
  {
    type: 'owner-profile',
    category: 'source',
    label: '用户画像',
    description: '获取 Owner Profile',
    icon: 'user-circle',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '画像', type: 'json' }],
    configSchema: {},
  },
  {
    type: 'person-load',
    category: 'source',
    label: '加载人设',
    description: '加载一个或所有人设',
    icon: 'users',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '人设列表', type: 'json' }],
    configSchema: {
      name: { type: 'string', label: '人名（留空加载全部）', placeholder: '张三', description: '指定某个人的名字，留空则返回所有人设' },
    },
  },
  {
    type: 'inspiration-load',
    category: 'source',
    label: '加载灵感',
    description: '加载灵感列表',
    icon: 'lightbulb',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '灵感列表', type: 'json' }],
    configSchema: {
      status: { type: 'select', label: '状态', options: ['', 'spark', 'incubating', 'mature', 'acted', 'archived'], optionLabels: ['全部状态', '✨ spark - 灵感火花', '🔬 incubating - 孵化中', '🌟 mature - 已成熟', '✅ acted - 已行动', '📦 archived - 已归档'], description: '按灵感的生命周期状态过滤' },
      domain: { type: 'string', label: '领域', placeholder: 'tech、design、life...', description: '按灵感所属领域过滤，留空返回全部' },
    },
  },
  {
    type: 'http-request',
    category: 'source',
    label: 'HTTP 请求',
    description: '通用 HTTP 请求',
    icon: 'globe',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '响应', type: 'json' }],
    configSchema: {
      url: { type: 'string', label: 'URL', required: true, template: true, placeholder: 'https://api.example.com/data', description: '完整的请求地址，支持模板变量' },
      method: { type: 'select', label: '方法', options: ['GET', 'POST', 'PUT', 'DELETE'], default: 'GET', optionLabels: ['GET - 获取数据', 'POST - 提交数据', 'PUT - 更新数据', 'DELETE - 删除数据'] },
      headers: { type: 'textarea', label: 'Headers (JSON)', placeholder: '{"Authorization": "Bearer xxx", "Content-Type": "application/json"}', description: 'JSON 格式的请求头，每行一个键值对' },
      body: { type: 'textarea', label: 'Body', template: true, placeholder: '{"key": "value"}', description: 'POST/PUT 请求的正文内容，支持模板变量' },
    },
  },
  {
    type: 'previous-run',
    category: 'source',
    label: '上次运行',
    description: '引用本 Pipeline 上次运行的某节点输出',
    icon: 'history',
    color: '#3B82F6',
    inputs: [],
    outputs: [{ id: 'out', label: '上次输出', type: 'any' }],
    configSchema: {
      node_id: { type: 'string', label: '节点 ID', required: true, placeholder: 'llm_chat_17xxx', description: '目标节点的 ID（在节点属性面板中查看）' },
    },
  },
  {
    type: 'rss-fetch',
    category: 'source',
    label: 'RSS 订阅',
    description: '抓取 RSS/Atom 订阅源，获取最新文章列表',
    icon: 'rss',
    color: '#F97316',
    inputs: [],
    outputs: [{ id: 'out', label: '文章列表', type: 'json' }],
    configSchema: {
      url: { type: 'string', label: 'RSS/Atom URL', required: true, template: true, placeholder: 'https://www.ruanyifeng.com/blog/atom.xml', description: '订阅源地址，支持 RSS 2.0 和 Atom 格式' },
      limit: { type: 'number', label: '最大条数', default: 10, description: '最多抓取多少篇文章，建议 5-20' },
      since_hours: { type: 'number', label: '时间范围（小时）', placeholder: '24', description: '只保留最近 N 小时内的文章，留空不过滤' },
      include_content: { type: 'select', label: '包含正文', options: ['false', 'true'], default: 'false', optionLabels: ['false - 仅标题+摘要（节省 Token）', 'true - 包含完整正文'], description: '是否抓取文章正文内容，正文较长会消耗更多 Token' },
    },
  },
  {
    type: 'web-scrape',
    category: 'source',
    label: '网页抓取',
    description: '抓取指定网页并提取正文内容',
    icon: 'file-scan',
    color: '#F97316',
    inputs: [],
    outputs: [{ id: 'out', label: '网页内容', type: 'json' }],
    configSchema: {
      url: { type: 'string', label: '网页 URL', required: true, template: true, placeholder: 'https://example.com/article', description: '要抓取的网页地址，支持模板变量' },
      extract_mode: { type: 'select', label: '提取模式', options: ['readability', 'raw', 'selector'], default: 'readability', optionLabels: ['readability - 智能提取正文', 'raw - 全页面去标签', 'selector - CSS 选择器'], description: 'readability 自动识别文章正文，selector 用 CSS 选择器精确提取' },
      selector: { type: 'string', label: 'CSS 选择器', placeholder: '.article-content、#main、article', description: '仅 selector 模式有效，支持标签名、.class、#id' },
      max_length: { type: 'number', label: '最大字符数', default: 5000, description: '提取内容的最大长度，超出会截断' },
    },
  },
  {
    type: 'web-search',
    category: 'source',
    label: '网络搜索',
    description: '搜索互联网获取相关结果',
    icon: 'search',
    color: '#F97316',
    inputs: [],
    outputs: [{ id: 'out', label: '搜索结果', type: 'json' }],
    configSchema: {
      query: { type: 'string', label: '搜索关键词', required: true, template: true, placeholder: 'MiniMem AI memory agent', description: '搜索关键词，支持模板变量动态生成' },
      max_results: { type: 'number', label: '最大结果数', default: 5, description: '返回几条搜索结果，建议 3-10' },
    },
  },
  {
    type: 'github-trending',
    category: 'source',
    label: 'GitHub Trending',
    description: '获取 GitHub 热门仓库列表',
    icon: 'github',
    color: '#F97316',
    inputs: [],
    outputs: [{ id: 'out', label: '热门仓库', type: 'json' }],
    configSchema: {
      language: { type: 'string', label: '编程语言', placeholder: 'typescript、python、rust...', description: '按编程语言过滤，留空获取所有语言的热门项目' },
      since: { type: 'select', label: '时间范围', options: ['daily', 'weekly', 'monthly'], default: 'daily', optionLabels: ['daily - 今日热门', 'weekly - 本周热门', 'monthly - 本月热门'] },
      limit: { type: 'number', label: '最大数量', default: 10, description: '返回多少个热门仓库，建议 5-15' },
    },
  },
  // 转换
  {
    type: 'filter',
    category: 'transform',
    label: '过滤',
    description: '按条件过滤数据',
    icon: 'filter',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '过滤结果', type: 'any' }],
    configSchema: {
      condition: { type: 'string', label: '条件表达式', required: true, placeholder: 'importance > 0.7', description: '支持 JS 表达式，可用字段如 importance、content、source、domain 等' },
    },
  },
  {
    type: 'sort',
    category: 'transform',
    label: '排序',
    description: '按字段排序',
    icon: 'arrow-up-down',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '排序结果', type: 'any' }],
    configSchema: {
      field: { type: 'string', label: '排序字段', required: true, placeholder: 'created_at、importance、content...', description: '排序依据的字段名，常用：created_at(时间)、importance(重要性)、temperature(温度)' },
      order: { type: 'select', label: '排序方向', options: ['asc', 'desc'], default: 'desc', optionLabels: ['asc - 升序（从小到大）', 'desc - 降序（从大到小）'] },
    },
  },
  {
    type: 'merge',
    category: 'transform',
    label: '合并',
    description: '合并多个输入',
    icon: 'merge',
    color: '#8B5CF6',
    inputs: [
      { id: 'in_a', label: '输入A', type: 'any' },
      { id: 'in_b', label: '输入B', type: 'any' },
    ],
    outputs: [{ id: 'out', label: '合并结果', type: 'any' }],
    configSchema: {
      mode: { type: 'select', label: '合并模式', options: ['concat', 'zip', 'object'], default: 'concat', optionLabels: ['concat - 拼接为一个列表', 'zip - 按位置一一配对', 'object - 合并为对象 {a: ..., b: ...}'], description: '两个输入数据的合并方式' },
    },
  },
  {
    type: 'template',
    category: 'transform',
    label: '文本模板',
    description: 'Handlebars 模板渲染',
    icon: 'file-code',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '上下文', type: 'any' }],
    outputs: [{ id: 'out', label: '渲染文本', type: 'text' }],
    configSchema: {
      template: { type: 'textarea', label: '模板内容', required: true, template: true, placeholder: '# {{$date}} 报告\n\n{{#each input}}\n- {{this.content}}\n{{/each}}', description: '使用 Handlebars 语法，input 指代上游数据' },
    },
  },
  {
    type: 'limit',
    category: 'transform',
    label: '截取',
    description: '截取前 N 条',
    icon: 'scissors',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '截取结果', type: 'any' }],
    configSchema: {
      count: { type: 'number', label: '数量', required: true, default: 10, description: '保留列表中的前 N 条数据' },
    },
  },
  {
    type: 'group-by',
    category: 'transform',
    label: '分组',
    description: '按字段分组',
    icon: 'layers',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '分组结果', type: 'json' }],
    configSchema: {
      field: { type: 'string', label: '分组字段', required: true, placeholder: 'domain、source、layer...', description: '按哪个字段分组，相同值的数据会归为一组' },
    },
  },
  {
    type: 'json-path',
    category: 'transform',
    label: 'JSON 提取',
    description: '提取 JSON 子路径',
    icon: 'braces',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '提取结果', type: 'any' }],
    configSchema: {
      path: { type: 'string', label: 'JSONPath', required: true, placeholder: '$.memories[*].content', description: 'JSONPath 表达式，$ 代表根节点，[*] 遍历数组' },
    },
  },
  {
    type: 'split',
    category: 'transform',
    label: '拆分',
    description: '将列表拆成单项逐个处理',
    icon: 'split',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '列表', type: 'any' }],
    outputs: [{ id: 'out', label: '拆分结果', type: 'any' }],
    configSchema: {},
  },
  {
    type: 'deduplicate',
    category: 'transform',
    label: '去重',
    description: '按字段去重',
    icon: 'copy-minus',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '去重结果', type: 'any' }],
    configSchema: {
      field: { type: 'string', label: '去重字段', required: true, placeholder: 'content、id...', description: '依据哪个字段判断重复，值相同的只保留一条' },
    },
  },
  {
    type: 'javascript',
    category: 'transform',
    label: 'JS 表达式',
    description: '自定义 JavaScript 表达式',
    icon: 'code',
    color: '#8B5CF6',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '输出', type: 'any' }],
    configSchema: {
      code: { type: 'textarea', label: '代码片段', required: true, placeholder: 'return input.map(i => i.content)', description: '可直接使用 input 变量（即上游数据），必须 return 返回结果' },
    },
  },
  // AI / LLM
  {
    type: 'llm-chat',
    category: 'ai',
    label: 'LLM 对话',
    description: '单轮 LLM 调用',
    icon: 'bot',
    color: '#F59E0B',
    inputs: [{ id: 'in', label: '上下文', type: 'any' }],
    outputs: [{ id: 'out', label: '输出文本', type: 'text' }],
    configSchema: {
      system_prompt: { type: 'textarea', label: 'System Prompt', template: true, placeholder: '你是一个专业的记忆分析助手，擅长从碎片化信息中总结规律。', description: '设定 AI 的角色和行为，影响输出风格和质量' },
      user_prompt: { type: 'textarea', label: 'User Prompt', required: true, template: true, placeholder: '请分析以下记忆内容并生成总结报告：\n\n{{nodes.memory_search_xxx.output}}', description: '用 {{nodes.节点ID.output}} 引用上游数据' },
      model: { type: 'string', label: '模型', placeholder: '留空使用全局默认', description: '指定 LLM 模型名称，如 gpt-4、qwen-plus 等' },
      temperature: { type: 'number', label: '温度', placeholder: '留空使用全局默认', description: '0-2 之间，越低越确定，越高越有创意。推荐：分析类 0.3，创作类 0.8' },
      max_tokens: { type: 'number', label: '最大 Token', placeholder: '留空使用全局默认', description: '输出最大长度限制，1 个中文字约 2 Token' },
    },
  },
  {
    type: 'llm-structured',
    category: 'ai',
    label: '结构化输出',
    description: 'LLM 结构化 JSON 输出',
    icon: 'braces',
    color: '#F59E0B',
    inputs: [{ id: 'in', label: '上下文', type: 'any' }],
    outputs: [{ id: 'out', label: 'JSON', type: 'json' }],
    configSchema: {
      system_prompt: { type: 'textarea', label: 'System Prompt', template: true, placeholder: '你是一个信息提取助手，按要求的 JSON 格式输出。', description: '设定 AI 角色，引导其输出结构化 JSON' },
      user_prompt: { type: 'textarea', label: 'User Prompt', required: true, template: true, placeholder: '从以下记忆中提取关键事件：\n\n{{nodes.xxx.output}}', description: '描述你的需求，LLM 会按 Output Schema 格式返回 JSON' },
      output_schema: { type: 'textarea', label: 'Output JSON Schema', required: true, placeholder: '{\n  "type": "object",\n  "properties": {\n    "events": {\n      "type": "array",\n      "items": {\n        "type": "object",\n        "properties": {\n          "title": {"type": "string"},\n          "date": {"type": "string"}\n        }\n      }\n    }\n  }\n}', description: '定义输出的 JSON 结构，LLM 会严格按此格式返回' },
      model: { type: 'string', label: '模型', placeholder: '留空使用全局默认' },
    },
  },
  {
    type: 'llm-summarize',
    category: 'ai',
    label: '摘要',
    description: '长文本自动摘要',
    icon: 'file-minus',
    color: '#F59E0B',
    inputs: [{ id: 'in', label: '文本', type: 'text' }],
    outputs: [{ id: 'out', label: '摘要', type: 'text' }],
    configSchema: {
      max_chunk_size: { type: 'number', label: '分段大小', default: 4000, description: '每次处理的最大字符数，超长文本会自动分段' },
      strategy: { type: 'select', label: '策略', options: ['single', 'map-reduce'], default: 'single', optionLabels: ['single - 单次摘要（适合短文本）', 'map-reduce - 分段后合并（适合长文本）'], description: '短文本用 single，长文本用 map-reduce 先分段摘要再合并' },
      model: { type: 'string', label: '模型', placeholder: '留空使用全局默认' },
    },
  },
  {
    type: 'llm-extract',
    category: 'ai',
    label: '信息提取',
    description: '从文本中提取结构化信息',
    icon: 'scan-text',
    color: '#F59E0B',
    inputs: [{ id: 'in', label: '文本', type: 'text' }],
    outputs: [{ id: 'out', label: 'JSON', type: 'json' }],
    configSchema: {
      fields: { type: 'textarea', label: '提取字段定义 (JSON)', required: true, placeholder: '[{"name": "title", "type": "string"}, {"name": "date", "type": "string"}, {"name": "sentiment", "type": "string"}]', description: '定义要提取的字段，每个字段有 name(字段名) 和 type(类型)' },
      model: { type: 'string', label: '模型', placeholder: '留空使用全局默认' },
    },
  },
  {
    type: 'llm-judge',
    category: 'ai',
    label: 'LLM 判断',
    description: 'LLM 做判断/打分',
    icon: 'scale',
    color: '#F59E0B',
    inputs: [{ id: 'in', label: '上下文', type: 'any' }],
    outputs: [{ id: 'out', label: '判断结果', type: 'json' }],
    configSchema: {
      system_prompt: { type: 'textarea', label: 'System Prompt', template: true, placeholder: '你是一个公正的评判者，根据标准打分。', description: '设定评判者角色和评判原则' },
      user_prompt: { type: 'textarea', label: 'User Prompt', required: true, template: true, placeholder: '请对以下内容进行质量评估：\n\n{{nodes.xxx.output}}', description: '描述评判任务，LLM 会返回 JSON 格式的判断结果' },
      criteria: { type: 'textarea', label: '判断标准', placeholder: '1. 内容是否完整 (1-5分)\n2. 逻辑是否清晰 (1-5分)\n3. 可操作性 (1-5分)', description: '列出具体的评判维度和标准' },
      model: { type: 'string', label: '模型', placeholder: '留空使用全局默认' },
    },
  },
  // 输出
  {
    type: 'output-file',
    category: 'output',
    label: '写入文件',
    description: '将结果写入本地文件',
    icon: 'file-output',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      path_template: { type: 'string', label: '文件路径模板', required: true, template: true, placeholder: 'reports/{{$date}}.md', description: '文件保存路径，可用 {{$date}} 自动按日期命名' },
      format: { type: 'select', label: '格式', options: ['md', 'json', 'txt', 'csv'], default: 'md', optionLabels: ['md - Markdown 格式', 'json - JSON 格式', 'txt - 纯文本', 'csv - 表格（逗号分隔）'] },
    },
  },
  {
    type: 'output-console',
    category: 'output',
    label: '保存报告',
    description: '保存到 Console 报告',
    icon: 'monitor',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      title_template: { type: 'string', label: '报告标题模板', required: true, template: true, placeholder: '{{$date}} 每日回顾', description: '报告的标题，会显示在 Console 报告列表中' },
    },
  },
  {
    type: 'output-minimem',
    category: 'output',
    label: '写回 MiniMem',
    description: '将结果作为记忆写回 MiniMem',
    icon: 'brain',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      tags: { type: 'string', label: '标签（逗号分隔）', placeholder: 'review, daily, auto-generated', description: '给写入的记忆打标签，方便后续过滤和搜索' },
      source: { type: 'string', label: '来源', default: 'minimem-console', placeholder: 'minimem-console', description: '标识这条记忆的来源，默认为 minimem-console' },
      content_type: { type: 'string', label: '内容类型', placeholder: 'report、summary、insight...', description: '记忆的内容类型标识，便于分类' },
      importance: { type: 'number', label: '重要性', placeholder: '0.5', description: '0-1 之间，0 最不重要，1 最重要。留空自动评估' },
    },
  },
  {
    type: 'output-webhook',
    category: 'output',
    label: 'Webhook',
    description: '发送 HTTP 通知',
    icon: 'webhook',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      url: { type: 'string', label: 'Webhook URL', required: true, placeholder: 'https://hooks.slack.com/services/xxx', description: '目标 Webhook 地址，如 Slack、飞书、企微机器人等' },
      method: { type: 'select', label: '方法', options: ['POST', 'PUT'], default: 'POST', optionLabels: ['POST - 发送新数据', 'PUT - 更新已有数据'] },
      headers: { type: 'textarea', label: 'Headers (JSON)', placeholder: '{"Content-Type": "application/json"}', description: 'JSON 格式的自定义请求头' },
      body_template: { type: 'textarea', label: 'Body 模板', template: true, placeholder: '{"text": "Pipeline 运行完毕：{{nodes.xxx.output}}"}', description: '请求体模板，可引用上游节点数据' },
    },
  },
  {
    type: 'output-email',
    category: 'output',
    label: '发送邮件',
    description: '发送邮件通知（需配置 SMTP）',
    icon: 'mail',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      to: { type: 'string', label: '收件人', required: true, placeholder: 'user@example.com', description: '收件人邮箱地址，多个用逗号分隔' },
      subject_template: { type: 'string', label: '标题模板', required: true, template: true, placeholder: '{{$date}} 每日记忆报告', description: '邮件标题，支持模板变量' },
      body_format: { type: 'select', label: '格式', options: ['text', 'html', 'markdown'], default: 'text', optionLabels: ['text - 纯文本', 'html - HTML 格式', 'markdown - Markdown 渲染'] },
    },
  },
  {
    type: 'output-variable',
    category: 'output',
    label: '存为变量',
    description: '存为 Pipeline 变量，供后续运行引用',
    icon: 'variable',
    color: '#10B981',
    inputs: [{ id: 'in', label: '内容', type: 'any' }],
    outputs: [],
    configSchema: {
      variable_name: { type: 'string', label: '变量名', required: true, placeholder: 'last_result', description: '变量名（英文），后续通过 {{vars.变量名}} 引用' },
    },
  },
  // 控制流
  {
    type: 'if-else',
    category: 'control',
    label: '条件分支',
    description: '根据条件走不同分支',
    icon: 'git-branch',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [
      { id: 'true', label: 'True', type: 'any' },
      { id: 'false', label: 'False', type: 'any' },
    ],
    configSchema: {
      condition: { type: 'string', label: '条件表达式', required: true, placeholder: 'input.length > 0', description: 'JS 表达式，为真走 True 分支，为假走 False 分支。input 指上游数据' },
    },
  },
  {
    type: 'loop',
    category: 'control',
    label: '循环',
    description: '对列表每一项执行处理',
    icon: 'repeat',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '列表', type: 'any' }],
    outputs: [{ id: 'item', label: '当前项', type: 'any' }],
    configSchema: {
      max_iterations: { type: 'number', label: '最大迭代数（0=不限）', default: 0, description: '安全限制：最多循环几次，0 表示不限制' },
    },
  },
  {
    type: 'switch',
    category: 'control',
    label: '多路分支',
    description: '根据表达式值匹配 case，路由到不同分支',
    icon: 'git-fork',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [
      { id: 'case_0', label: 'Case 0', type: 'any' },
      { id: 'case_1', label: 'Case 1', type: 'any' },
      { id: 'case_2', label: 'Case 2', type: 'any' },
      { id: 'default', label: 'Default', type: 'any' },
    ],
    configSchema: {
      expression: { type: 'string', label: '表达式', required: true, placeholder: 'input.status', description: 'JS 表达式，返回值会与 Case 列表中的 value 比较' },
      cases: { type: 'textarea', label: 'Case 列表 (JSON)', required: true, placeholder: '[{"value": "active", "port": "case_0"}, {"value": "archived", "port": "case_1"}]', description: '匹配规则：value 匹配则走对应 port，都不匹配走 default' },
    },
  },
  {
    type: 'parallel',
    category: 'control',
    label: '并行分发',
    description: '将数据同时发送到多个下游分支',
    icon: 'columns',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [
      { id: 'out_0', label: '分支 0', type: 'any' },
      { id: 'out_1', label: '分支 1', type: 'any' },
      { id: 'out_2', label: '分支 2', type: 'any' },
    ],
    configSchema: {
      branches: { type: 'number', label: '分支数', required: true, default: 2, description: '并行分发到几个分支（2-3）' },
    },
  },
  {
    type: 'wait-all',
    category: 'control',
    label: '汇聚',
    description: '等待所有输入就绪后合并输出',
    icon: 'combine',
    color: '#EF4444',
    inputs: [
      { id: 'in_0', label: '输入 0', type: 'any' },
      { id: 'in_1', label: '输入 1', type: 'any' },
      { id: 'in_2', label: '输入 2', type: 'any' },
    ],
    outputs: [{ id: 'out', label: '合并结果', type: 'any' }],
    configSchema: {
      merge_mode: { type: 'select', label: '合并模式', options: ['object', 'array', 'first'], default: 'object', optionLabels: ['object - 合并为对象 {in_0: ..., in_1: ...}', 'array - 合并为数组 [...]', 'first - 只取第一个完成的'], description: '多个输入数据的合并方式' },
    },
  },
  {
    type: 'retry',
    category: 'control',
    label: '重试',
    description: '验证输入有效性，失败时提供重试策略',
    icon: 'refresh-cw',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '输出', type: 'any' }],
    configSchema: {
      max_retries: { type: 'number', label: '最大重试次数', default: 3, description: '最多重试几次，推荐 2-5 次' },
      delay_ms: { type: 'number', label: '重试延迟 (ms)', default: 1000, description: '每次重试前等待的时间（毫秒），1000 = 1 秒' },
      backoff_multiplier: { type: 'number', label: '退避倍率', default: 2, description: '每次重试延迟翻几倍，2 表示 1s → 2s → 4s → 8s' },
      validation: { type: 'string', label: '验证表达式', placeholder: 'input !== null && input.status === "ok"', description: '验证结果是否有效的 JS 表达式，返回 false 则触发重试' },
    },
  },
  {
    type: 'delay',
    category: 'control',
    label: '延迟',
    description: '等待指定时间后透传数据',
    icon: 'clock',
    color: '#EF4444',
    inputs: [{ id: 'in', label: '输入', type: 'any' }],
    outputs: [{ id: 'out', label: '输出', type: 'any' }],
    configSchema: {
      delay_ms: { type: 'number', label: '延迟时间 (ms)', required: true, default: 1000, description: '等待多久再传递数据（毫秒），1000 = 1 秒' },
    },
  },
  {
    type: 'error-handler',
    category: 'control',
    label: '错误处理',
    description: '捕获错误并提供兜底值',
    icon: 'shield-alert',
    color: '#EF4444',
    inputs: [
      { id: 'data', label: '正常数据', type: 'any' },
      { id: 'error', label: '错误信息', type: 'any' },
    ],
    outputs: [
      { id: 'out', label: '输出', type: 'any' },
      { id: 'had_error', label: '是否出错', type: 'any' },
    ],
    configSchema: {
      fallback_value: { type: 'textarea', label: '兜底值模板', template: true, placeholder: '{"status": "fallback", "error": "{{error}}"}', description: '上游出错时返回的默认值，可用 {{error}} 引用错误信息' },
      log_error: { type: 'select', label: '记录错误日志', options: ['true', 'false'], default: 'true', optionLabels: ['true - 记录到日志', 'false - 静默忽略'] },
    },
  },
  // MiniMem 操作
  {
    type: 'dream-trigger',
    category: 'action',
    label: '触发 Dream',
    description: '触发 MiniMem Dream',
    icon: 'moon',
    color: '#6366F1',
    inputs: [],
    outputs: [{ id: 'out', label: '结果', type: 'json' }],
    configSchema: {
      mode: { type: 'select', label: '模式', options: ['daily', 'weekly'], default: 'daily', optionLabels: ['daily - 每日整理（轻量快速）', 'weekly - 每周深度整理'], description: 'Dream 是 MiniMem 的记忆整理机制' },
      phases: { type: 'string', label: '阶段（逗号分隔）', placeholder: '1,2,3,4', description: '执行哪些阶段：1-压缩 2-关联 3-遗忘 4-反思。留空执行全部' },
    },
  },
  {
    type: 'memory-write',
    category: 'action',
    label: '写入记忆',
    description: '向 MiniMem 写入记忆',
    icon: 'pen-tool',
    color: '#6366F1',
    inputs: [{ id: 'in', label: '上下文', type: 'any' }],
    outputs: [{ id: 'out', label: '结果', type: 'json' }],
    configSchema: {
      content_template: { type: 'textarea', label: '内容模板', required: true, template: true, placeholder: '今日总结：{{nodes.llm_chat_xxx.output}}', description: '要写入的记忆内容，可引用上游节点数据' },
      source: { type: 'string', label: '来源', default: 'minimem-console', placeholder: 'minimem-console', description: '标识记忆来源，方便追溯' },
      tags: { type: 'string', label: '标签（逗号分隔）', placeholder: 'auto, daily-review', description: '给新记忆打标签' },
      importance: { type: 'number', label: '重要性', placeholder: '0.5', description: '0-1 之间，留空自动评估' },
    },
  },
  {
    type: 'memory-forget',
    category: 'action',
    label: '遗忘主题',
    description: '遗忘指定主题的记忆',
    icon: 'eraser',
    color: '#6366F1',
    inputs: [],
    outputs: [{ id: 'out', label: '结果', type: 'json' }],
    configSchema: {
      topic: { type: 'string', label: '遗忘主题', required: true, template: true, placeholder: '过期的项目进度、旧密码...', description: '要遗忘的主题描述，相关记忆会被标记为遗忘' },
      dry_run: { type: 'select', label: '模式', options: ['true', 'false'], default: 'true', optionLabels: ['true - 预览模式（只看不删）', 'false - 正式执行遗忘'], description: '建议先用预览模式确认影响范围' },
    },
  },
  {
    type: 'snapshot-create',
    category: 'action',
    label: '创建快照',
    description: '创建 MiniMem 快照',
    icon: 'camera',
    color: '#6366F1',
    inputs: [],
    outputs: [{ id: 'out', label: '结果', type: 'json' }],
    configSchema: {},
  },
];
